CREATE TABLE IF NOT EXISTS messages
(
    id   INT AUTO_INCREMENT PRIMARY KEY,
    text VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS User
(
    id       INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    password VARCHAR(50) NOT NULL,
    name     VARCHAR(20) NOT NULL
);
